name: Trigger auto deployment for reactbasic84f29c7dbc55

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/reactbasic84f29c7dbc55-AutoDeployTrigger-d41e7591-ad55-4dab-8e13-5e1a0b198327.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REACTBASIC84F29C7DBC55_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REACTBASIC84F29C7DBC55_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REACTBASIC84F29C7DBC55_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.REACTBASIC84F29C7DBC55_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REACTBASIC84F29C7DBC55_REGISTRY_PASSWORD }}
          containerAppName: reactbasic84f29c7dbc55
          resourceGroup: reactbasic84f29c7d
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


